const data = {

    'TCL': {
        '香港': { 'direction_name': ['香港'], 'direction_id': ['up'] },     
        '九龍': { 'direction_name': ['香港', '東涌'], 'direction_id': ['up', 'down'] },   
        '奧運': { 'direction_name': ['香港', '東涌'], 'direction_id': ['up', 'down'] },   
        '南昌': { 'direction_name': ['香港', '東涌'], 'direction_id': ['up', 'down'] },   
        '茘景': { 'direction_name': ['香港', '東涌'], 'direction_id': ['up', 'down'] },   
        '青衣': { 'direction_name': ['香港', '東涌'], 'direction_id': ['up', 'down'] },   
        '欣澳': { 'direction_name': ['香港', '東涌'], 'direction_id': ['up', 'down'] },
        '東涌': { 'direction_name': ['香港'], 'direction_id': ['down'] },
    },

    'TML': {
        '烏溪沙':   { 'direction_name': ['屯門'], 'direction_id': ['up'] },
        '馬鞍山':   { 'direction_name': ['屯門', '烏溪沙'], 'direction_id': ['up', 'down'] },
        '恆安':     { 'direction_name': ['屯門', '烏溪沙'], 'direction_id': ['up', 'down'] },
        '大水坑':   { 'direction_name': ['屯門', '烏溪沙'], 'direction_id': ['up', 'down'] },
        '石門':     { 'direction_name': ['屯門', '烏溪沙'], 'direction_id': ['up', 'down'] },
        '第一城':   { 'direction_name': ['屯門', '烏溪沙'], 'direction_id': ['up', 'down'] },
        '沙田圍':   { 'direction_name': ['屯門', '烏溪沙'], 'direction_id': ['up', 'down'] },
        '車公廟':   { 'direction_name': ['屯門', '烏溪沙'], 'direction_id': ['up', 'down'] },
        '大圍':     { 'direction_name': ['屯門', '烏溪沙'], 'direction_id': ['up', 'down'] },
        '顯徑':     { 'direction_name': ['屯門', '烏溪沙'], 'direction_id': ['up', 'down'] },
        '鑽石山':   { 'direction_name': ['屯門', '烏溪沙'], 'direction_id': ['up', 'down'] },
        '啟德':     { 'direction_name': ['屯門', '烏溪沙'], 'direction_id': ['up', 'down'] },
        '宋皇臺':   { 'direction_name': ['屯門', '烏溪沙'], 'direction_id': ['up', 'down'] },
        '土瓜灣':   { 'direction_name': ['屯門', '烏溪沙'], 'direction_id': ['up', 'down'] },
        '何文田':   { 'direction_name': ['屯門', '烏溪沙'], 'direction_id': ['up', 'down'] },
        '紅磡':     { 'direction_name': ['屯門', '烏溪沙'], 'direction_id': ['up', 'down'] },
        '尖東':     { 'direction_name': ['屯門', '烏溪沙'], 'direction_id': ['up', 'down'] },
        '柯士甸':   { 'direction_name': ['屯門', '烏溪沙'], 'direction_id': ['up', 'down'] },
        '南昌':     { 'direction_name': ['屯門', '烏溪沙'], 'direction_id': ['up', 'down'] },
        '美孚':     { 'direction_name': ['屯門', '烏溪沙'], 'direction_id': ['up', 'down'] },
        '荃灣西':   { 'direction_name': ['屯門', '烏溪沙'], 'direction_id': ['up', 'down'] },
        '錦上路':   { 'direction_name': ['屯門', '烏溪沙'], 'direction_id': ['up', 'down'] },
        '元朗':     { 'direction_name': ['屯門', '烏溪沙'], 'direction_id': ['up', 'down'] },
        '朗屏':     { 'direction_name': ['屯門', '烏溪沙'], 'direction_id': ['up', 'down'] },
        '天水圍':   { 'direction_name': ['屯門', '烏溪沙'], 'direction_id': ['up', 'down'] },
        '兆康':     { 'direction_name': ['屯門', '烏溪沙'], 'direction_id': ['up', 'down'] },
        '屯門':     { 'direction_name': ['烏溪沙'], 'direction_id': ['down'] },
    },

    'LRT': {
        '屯門碼頭':     { 'direction_name': ['2', '3', '4', '5'], 'direction_id': ['2', '3', '4', '5'] },
        '美樂':         { 'direction_name': ['1', '2'], 'direction_id': ['1', '2'] },
        '蝴蝶':         { 'direction_name': ['1', '2'], 'direction_id': ['1', '2'] },
        '輕鐵車廠':     { 'direction_name': ['1', '2'], 'direction_id': ['1', '2'] },
        '龍門':         { 'direction_name': ['1', '2'], 'direction_id': ['1', '2'] },
        '青山村':       { 'direction_name': ['1', '2'], 'direction_id': ['1', '2'] },
        '青雲':         { 'direction_name': ['1', '2'], 'direction_id': ['1', '2'] },
        '建安':         { 'direction_name': ['1', '2'], 'direction_id': ['1', '2'] },
        '河田':         { 'direction_name': ['1', '2'], 'direction_id': ['1', '2'] },
        '蔡意橋':       { 'direction_name': ['1', '2'], 'direction_id': ['1', '2'] },
        '澤豐':         { 'direction_name': ['1', '2'], 'direction_id': ['1', '2'] },
        '屯門醫院':     { 'direction_name': ['1', '2'], 'direction_id': ['1', '2'] },
        '兆康':         { 'direction_name': ['1', '2', '5', '6'], 'direction_id': ['1', '2', '5', '6'] },
        '麒麟':         { 'direction_name': ['1', '2'], 'direction_id': ['1', '2'] },
        '青松':         { 'direction_name': ['1', '2'], 'direction_id': ['1', '2'] },
        '建生':         { 'direction_name': ['1', '2'], 'direction_id': ['1', '2'] },
        '田景':         { 'direction_name': ['1', '2'], 'direction_id': ['1', '2'] },
        '良景':         { 'direction_name': ['1', '2'], 'direction_id': ['1', '2'] },
        '新圍':         { 'direction_name': ['1', '2'], 'direction_id': ['1', '2'] },
        '石排':         { 'direction_name': ['1', '2'], 'direction_id': ['1', '2'] },
        '山景 (北)':    { 'direction_name': ['1'], 'direction_id': ['1'] },
        '山景 (南)':    { 'direction_name': ['1'], 'direction_id': ['1'] },
        '鳴琴':         { 'direction_name': ['1', '2'], 'direction_id': ['1', '2'] },
        '大興 (北)':    { 'direction_name': ['1', '2'], 'direction_id': ['1', '2'] },
        '大興 (南)':    { 'direction_name': ['1', '2'], 'direction_id': ['1', '2'] },
        '銀圍':         { 'direction_name': ['1', '2'], 'direction_id': ['1', '2'] },
        '兆禧':         { 'direction_name': ['1', '2'], 'direction_id': ['1', '2'] },
        '屯門泳池':     { 'direction_name': ['1', '2'], 'direction_id': ['1', '2'] },
        '豐景園':       { 'direction_name': ['1', '2'], 'direction_id': ['1', '2'] },
        '兆麟':         { 'direction_name': ['1', '2'], 'direction_id': ['1', '2'] },
        '安定':         { 'direction_name': ['1', '2'], 'direction_id': ['1', '2'] },
        '友愛':         { 'direction_name': ['1'], 'direction_id': ['1'] },
        '市中心':       { 'direction_name': ['1', '4'], 'direction_id': ['1', '4'] },
        '屯門':         { 'direction_name': ['1', '2'], 'direction_id': ['1', '2'] },
        '杯渡':         { 'direction_name': ['1', '2'], 'direction_id': ['1', '2'] },
        '何福堂':       { 'direction_name': ['1', '2'], 'direction_id': ['1', '2'] },
        '新墟':         { 'direction_name': ['1', '2'], 'direction_id': ['1', '2'] },
        '景峰':         { 'direction_name': ['1', '2'], 'direction_id': ['1', '2'] },
        '鳳地':         { 'direction_name': ['1', '2'], 'direction_id': ['1', '2'] },
        '藍地':         { 'direction_name': ['1', '2'], 'direction_id': ['1', '2'] },
        '泥圍':         { 'direction_name': ['1', '2'], 'direction_id': ['1', '2'] },
        '鍾屋村':       { 'direction_name': ['1', '2'], 'direction_id': ['1', '2'] },
        '洪水橋':       { 'direction_name': ['1', '2'], 'direction_id': ['1', '2'] },
        '塘坊村':       { 'direction_name': ['1', '2'], 'direction_id': ['1', '2'] },
        '屏山':         { 'direction_name': ['1', '2'], 'direction_id': ['1', '2'] },
        '坑尾村':       { 'direction_name': ['1', '2'], 'direction_id': ['1', '2'] },
        '天水圍':       { 'direction_name': ['1', '2', '3'], 'direction_id': ['1', '2', '3'] },
        '天慈':         { 'direction_name': ['1', '2'], 'direction_id': ['1', '2'] },
        '天耀':         { 'direction_name': ['1', '2'], 'direction_id': ['1', '2'] },
        '樂湖':         { 'direction_name': ['1', '2'], 'direction_id': ['1', '2'] },
        '天湖':         { 'direction_name': ['1', '2'], 'direction_id': ['1', '2'] },
        '銀座':         { 'direction_name': ['1', '2'], 'direction_id': ['1', '2'] },
        '天瑞':         { 'direction_name': ['1', '2'], 'direction_id': ['1', '2'] },
        '頌富':         { 'direction_name': ['1', '2'], 'direction_id': ['1', '2'] },
        '天富':         { 'direction_name': ['1', '2'], 'direction_id': ['1', '2'] },
        '翠湖':         { 'direction_name': ['1', '2'], 'direction_id': ['1', '2'] },
        '天榮':         { 'direction_name': ['6', '7'], 'direction_id': ['6', '7'] },
        '天悅':         { 'direction_name': ['1', '2'], 'direction_id': ['1', '2'] },
        '天秀':         { 'direction_name': ['1', '2'], 'direction_id': ['1', '2'] },
        '濕地公園':     { 'direction_name': ['1', '2'], 'direction_id': ['1', '2'] },
        '天恒':         { 'direction_name': ['1', '2'], 'direction_id': ['1', '2'] },
        '天逸':         { 'direction_name': ['1', '2', '4', '5'], 'direction_id': ['1', '2', '4', '5'] },
        '水邊圍':       { 'direction_name': ['1', '2'], 'direction_id': ['1', '2'] },
        '豐年路':       { 'direction_name': ['1', '2'], 'direction_id': ['1', '2'] },
        '康樂路':       { 'direction_name': ['1', '2'], 'direction_id': ['1', '2'] },
        '大棠路':       { 'direction_name': ['1', '2'], 'direction_id': ['1', '2'] },
        '元朗':         { 'direction_name': ['2', '3', '4', '5'], 'direction_id': ['2', '3', '4', '5'] },
        '三聖':         { 'direction_name': ['1'], 'direction_id': ['1'] },
    }
}

const MTR_APITranslation = {

    '烏溪沙': 'WKS',
    '馬鞍山': 'MOS',
    '恆安': 'HEO',
    '大水坑': 'TSH',
    '石門': 'SHM',
    '第一城': 'CIO',
    '沙田圍': 'STW',
    '車公廟': 'CKT',
    '大圍': 'TAW',
    '顯徑': 'HIK',
    '鑽石山': 'DIH',
    '啟德': 'KAT',
    '宋皇臺': 'SUW',
    '土瓜灣': 'TKW',
    '何文田': 'HOM',
    '紅磡': 'HUH',
    '尖東': 'ETS',
    '柯士甸': 'AUS',
    '南昌': 'NAC',
    '美孚': 'MEF',
    '荃灣西': 'TWW',
    '錦上路': 'KSR',
    '元朗': 'YUL',
    '朗屏': 'LOP',
    '天水圍': 'TIS',
    '兆康': 'SIH',
    '屯門': 'TUM',
    '香港': 'HOK',
    '九龍': 'KOW',
    '奧運': 'OLY',
    '茘景': 'LAK',
    '青衣': 'TSY',
    '欣澳': 'SUN',
    '東涌': 'TUC',

}

const LR_APITranslation = {

    '屯門碼頭': '1',
    '美樂': '10',
    '蝴蝶': '15',
    '輕鐵車廠': '20',
    '龍門': '30',
    '青山村': '40',
    '青雲': '50',
    '建安': '60',
    '河田': '70',
    '蔡意橋': '75',
    '澤豐': '80',
    '屯門醫院': '90',
    '兆康': '100',
    '麒麟': '110',
    '青松': '120',
    '建生': '130',
    '田景': '140',
    '良景': '150',
    '新圍': '160',
    '石排': '170',
    '山景 (北)': '180',
    '山景 (南)': '190',
    '鳴琴': '200',
    '大興 (北)': '212',
    '大興 (南)': '220',
    '銀圍': '230',
    '兆禧': '240',
    '屯門泳池': '250',
    '豐景園': '260',
    '兆麟': '265',
    '安定': '270',
    '友愛': '275',
    '市中心': '280',
    '屯門': '295',
    '杯渡': '300',
    '何福堂': '310',
    '新墟': '320',
    '景峰': '330',
    '鳳地': '340',
    '藍地': '350',
    '泥圍': '360',
    '鍾屋村': '370',
    '洪水橋': '380',
    '塘坊村': '390',
    '屏山': '400',
    '坑尾村': '425',
    '天水圍': '430',
    '天慈': '435',
    '天耀': '445',
    '樂湖': '448',
    '天湖': '450',
    '銀座': '455',
    '天瑞': '460',
    '頌富': '468',
    '天富': '480',
    '翠湖': '490',
    '天榮': '500',
    '天悅': '510',
    '天秀': '520',
    '濕地公園': '530',
    '天恒': '540',
    '天逸': '550',
    '水邊圍': '560',
    '豐年路': '570',
    '康樂路': '580',
    '大棠路': '590',
    '元朗': '600',
    '三聖': '920',

}

export { data, LR_APITranslation, MTR_APITranslation }